
import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { Message, MessageRole } from '../types';
import { User, Anchor, Sparkles, Globe, FileText, Volume2, StopCircle } from 'lucide-react';

interface MessageBubbleProps {
  message: Message;
}

export const MessageBubble: React.FC<MessageBubbleProps> = ({ message }) => {
  const isUser = message.role === MessageRole.User;
  const [isSpeaking, setIsSpeaking] = useState(false);

  const handleSpeak = () => {
    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
    } else {
      const utterance = new SpeechSynthesisUtterance(message.text);
      utterance.onend = () => setIsSpeaking(false);
      utterance.onerror = () => setIsSpeaking(false);
      window.speechSynthesis.speak(utterance);
      setIsSpeaking(true);
    }
  };

  return (
    <div className={`flex w-full mb-6 ${isUser ? 'justify-end' : 'justify-start'}`}>
      <div className={`flex max-w-[85%] md:max-w-[75%] ${isUser ? 'flex-row-reverse' : 'flex-row'} gap-3`}>
        
        {/* Avatar */}
        <div className={`flex-shrink-0 w-7 h-7 rounded-md flex items-center justify-center border ${
          isUser 
            ? 'bg-zinc-800 text-zinc-400 border-zinc-700' 
            : 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20'
        }`}>
          {isUser ? <User size={14} /> : <Anchor size={14} />}
        </div>

        {/* Content */}
        <div className={`flex flex-col ${isUser ? 'items-end' : 'items-start'}`}>
          <div className={`px-4 py-3 rounded-2xl text-sm md:text-base shadow-sm ${
            isUser 
              ? 'bg-zinc-800 text-zinc-200 rounded-tr-none border border-zinc-700/50' 
              : 'bg-transparent text-zinc-300 rounded-tl-none px-0 py-0' 
          } ${!isUser && 'bg-zinc-900/40 border border-zinc-800/50'}`}> 
          
            {/* Attachments */}
            {message.attachments && message.attachments.length > 0 && (
              <div className="flex flex-wrap gap-2 mb-3">
                {message.attachments.map((att, idx) => {
                  if (att.mimeType.startsWith('image/')) {
                     return (
                      <img 
                        key={idx} 
                        src={`data:${att.mimeType};base64,${att.data}`} 
                        alt="attachment" 
                        className="max-w-[200px] max-h-[200px] rounded-lg border border-zinc-600 object-cover"
                      />
                     );
                  } else {
                     return (
                       <div key={idx} className="flex items-center gap-2 bg-zinc-900/50 border border-zinc-600 rounded-lg px-3 py-2 max-w-[200px]">
                          <div className="bg-zinc-700 p-1.5 rounded">
                             <FileText size={16} className="text-indigo-300" />
                          </div>
                          <div className="flex flex-col overflow-hidden">
                             <span className="text-xs font-medium truncate text-zinc-200">{att.name || 'File'}</span>
                             <span className="text-[10px] text-zinc-400 truncate">{att.mimeType}</span>
                          </div>
                       </div>
                     );
                  }
                })}
              </div>
            )}

            {/* Generated Image (Model output) */}
            {message.generatedImage && (
              <div className="mb-3">
                 <img 
                    src={`data:image/jpeg;base64,${message.generatedImage}`} 
                    alt="Generated by Ada" 
                    className="w-full max-w-md rounded-lg border border-indigo-500/30 shadow-lg shadow-indigo-500/10"
                  />
                  <div className="text-xs text-indigo-400 mt-1 flex items-center gap-1">
                    <Sparkles size={12} /> Generated with Imagen
                  </div>
              </div>
            )}

            {/* Text Content */}
            {message.text && (
              <div className="prose prose-invert prose-sm max-w-none prose-p:leading-relaxed prose-pre:bg-zinc-900 prose-pre:border prose-pre:border-zinc-800">
                <ReactMarkdown>{message.text}</ReactMarkdown>
              </div>
            )}
            
            {/* Thinking Indicator */}
            {!message.text && !message.generatedImage && message.role === MessageRole.Model && (
              <div className="flex items-center gap-2 text-zinc-500 text-xs italic">
                <Anchor size={12} className="animate-spin duration-3000" />
                <span>Processing...</span>
              </div>
            )}
          </div>

          {/* Action Row: Sources & TTS */}
          <div className="mt-1.5 flex items-center justify-between w-full px-1 opacity-0 group-hover:opacity-100 transition-opacity">
            
            {/* Grounding Sources */}
            <div className="flex flex-wrap gap-2">
              {message.groundingSources && message.groundingSources.map((source, idx) => (
                <a 
                  key={idx} 
                  href={source.uri} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="flex items-center gap-1 text-[10px] bg-zinc-900 hover:bg-zinc-800 text-indigo-400 px-2 py-0.5 rounded border border-zinc-800 transition-colors"
                >
                  <Globe size={10} />
                  <span className="truncate max-w-[150px]">{source.title || 'Source'}</span>
                </a>
              ))}
            </div>

            {/* TTS Button (Only for non-empty text) */}
            {message.text && (
              <button 
                onClick={handleSpeak}
                className={`p-1 rounded transition-colors ml-auto ${
                  isSpeaking ? 'text-indigo-400 bg-indigo-500/10 animate-pulse' : 'text-zinc-600 hover:text-zinc-400'
                }`}
                title={isSpeaking ? "Stop Speaking" : "Read Aloud"}
              >
                {isSpeaking ? <StopCircle size={12} /> : <Volume2 size={12} />}
              </button>
            )}
          </div>
          
          <div className="text-[9px] text-zinc-600 mt-0.5 px-1 font-mono">
            {new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
          </div>
        </div>
      </div>
    </div>
  );
};
